version: 1.1.{build}
image: Visual Studio 2019
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
nuget:
  project_feed: true
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
  project: Execute.HttpRequest.sln
test_script:
- OpenCover.Console.exe -register:user -filter:"+[Execute*]* -[*]*.Properties.*" -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\projects\execute-httprequest-scamo\UnitTests\bin\Debug\UnitTests.dll" -output:.\codecov_results.xml
- codecov -f .\codecov_results.xml
#deploy:
#  provider: https://ci.appveyor.com/nuget/execute-httprequest-tcrs65r3r7uh
#  api_key:
#    secure: FodyM5fyWKh4OyrkaIMa93LYWXXlg8Zy7zZbWaQmh5s=
#  skip_symbols: true
#  symbol_server:           # remove to push symbols to SymbolSource.org
#  artifact: /.*(\.|\.s)nupkg/
#deploy:
#  provider: https://ci.appveyor.com/nuget/execute-httprequest-tcrs65r3r7uh
#  api_key:
#    secure: FodyM5fyWKh4OyrkaIMa93LYWXXlg8Zy7zZbWaQmh5s=
#  skip_symbols: true
#  symbol_server:           # remove to push symbols to SymbolSource.org
#  artifact: /.*(\.|\.s)nupkg/
deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/nstevens1040/index.json
    artifact: /.nupkg/
    username: nstevens1040
    api_key:
      secure: f+MLRpFFOj9kyNxbFyIt2n5I/dR48bmJ6qXRB/ageJ/18o61FDhu61IZgwk9KfqD
  - provider: GitHub
    tag: v1.2.2
    release: v1.2.2 stable
    description: 'Pushing Quick-Start.ps1'
    auth_token:
      secure: ElzOGqa44YRqwJ9jKgjBNDbPEmxb1Mg3I+0TxsPQg8OdUSOA8T8DwkwoKofTXMQT
    artifact: /.*\.ps1/ 
    draft: false
    prerelease: false
artifacts:
  - path: quick-start.ps1
    name: QuickStart
    type: File
after_build:
- ps: >-
    "`n    [cmdletbinding()]`n    Param()`n    `$Assembly = [System.Convert]::FromBase64String(`"$([System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes("C:\projects\execute-httprequest-scamo\Execute.HttpRequest\bin\Debug\Execute.HttpRequest.dll")))`")`n    `$Execute_HttpRequest = [System.Reflection.Assembly]::Load(`$assembly)`n    if(`"Execute.HttpRequest`" -as [type])`n    {`n        Write-Host `"Assembly loaded successfully! `" -ForegroundColor Green -NoNewline`n        Write-Host `"[Execute.HttpRequest]`" -ForegroundColor Yellow`n    } else {`n        Write-Host `"Assembly failed to load: `" -ForegroundColor Yellow -NoNewline`n        Write-Host `"[Execute.HttpRequest]`" -ForegroundColor Red`n        return `$Error`n    }`n" | out-File C:\projects\execute-httprequest-scamo\Quick-Start.ps1 -encoding ascii; Push-AppveyorArtifact C:\projects\execute-httprequest-scamo\Quick-Start.ps1 -FileName Quick-Start.ps1
