version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: REi1da+SPjyI0mfeSExwzAkddTNgmLdMkyjq/RNtbpGH8Bo0IQqfEDWrAdbAiR4Z
  skip_symbols: true
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*(\.|\.s)nupkg/
